### ISSUE TITLE
Is it possible to release the dataset?

### ISSUE THREAD

**Issue by RonnieBickleman** [pillowlab/GLMspiketraintutorial#1]
I'm interested in this tutorial, but I found that the dataset is not included, is it possible to release the dataset or give a url in the readme.txt?

**Comment by jpillow** [comment]
Hi xingdong,

Thanks for your interest in the tutorial! I don't have permission to release the dataset publicly but if you email me I'd be happy to share it with you (pillow at princeton dot edu).

(I was planning to add a note to this effect in the README but hadn't gotten around to it.)

best,
Jonathan

**Comment by JialinKang** [comment]
great job! btw, can I have the dataset? my e-mail address is kangjl19@mails.tsinghua.edu.cn
