### ISSUE TITLE
What python version does this run in?

### ISSUE THREAD

**Issue by AngCamp** [pillowlab/GLMspiketraintutorial#3]
I'm not sure if this repo is being maintained.  What should my environment set up be?

**Comment by jpillow** [comment]
Yes, it is being maintained!  Although this is the matlab version of the tutorial.  

The python version (which uses python 3 and requires numpy, scipy, matplotlib, and statsmodels) lives here:  https://github.com/pillowlab/GLMspiketraintutorial_python
